### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by fsmanuel** [halo/bender#3]
I have this task to make sure that staging doesn't get indexed.
Should we include it into bender? I use it on every project...

``` rb
namespace :deploy do
  desc "Disallow robots unless deploying to production."
  task :disallow_robots do
    return if fetch(:stage) == :production

    on roles :app do |host|
      as fetch(:application) do
        within File.join(fetch(:deploy_to), 'public') do
          execute :echo, %{"User-agent: *\nDisallow: /\n" > robots.txt}
        end
      end
    end
  end
end

after "deploy:updating", "deploy:disallow_robots"
```

**Comment by halo** [comment]
Tricky. What if the project has such a file in the repository? Or if the file is dynamically generated with a controller?

You could add this in bender, but then I suggest it only creates the file if it is not already there. Or even better: Don't run the task by default. Let the end user decide whether to run this or not.

Even better: Use basic auth in staging, like I do :)

**Comment by fsmanuel** [comment]
Basic auth is no option if you need the site to be accessible by social sharing platforms to test the og tags for example.

I don't see why it should be a problem. In production you will serve the file you put into `public` or the dynamically generated one. Only staging serves the `Disallow /` and that is always what you want for your staging env.
But if you don't feel good about it, I'll just use the task in my projects.

**Comment by halo** [comment]
True, okay let's add it. It makes sense.

**Comment by fsmanuel** [comment]
I'll open a PR tomorrow.
