### ISSUE TITLE
Update to capistrano 3.5.0

### ISSUE THREAD

**Issue by fsmanuel** [halo/bender#8]
By the way, we should try capistrano `3.5.0` because [the changes](https://github.com/capistrano/capistrano/blob/master/CHANGELOG.md) are pretty small compared to `3.4.`. 

And I think [airbrush](https://github.com/mattbrictson/airbrussh#readme) is pretty neat. That way we could skip all the logging monkey patching alltogether!

**Comment by halo** [comment]
https://github.com/halo/bender/commit/b7105be886debb8742f71a24bc0616d4eac6ed20
